name = "uniswap"
version = "3.0.1"

[var.main]
owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
deployer = "0x6c9fc64a53c1b71fb3f9af64d1ae3a4931a5f4e9"
nativeCurrencyLabel = "ETH"

[clone.Core]
source = "uniswap-core:3.0.0"
options.deployer = "<%= settings.deployer %>"

[pull.WETH]
source = "weth-token"

[deploy.ProxyAdmin]
artifact = "ProxyAdmin"

[deploy.TickLens]
artifact = "TickLens"

[deploy.QuoterV2]
artifact = "QuoterV2"
args = [
    "<%= Core.UniswapV3Factory.address %>",
    "<%= WETH.Token.address %>",
]
depends = ["clone.Core", "pull.WETH"]

[deploy.SwapRouter]
artifact = "SwapRouter"
args = [
    "<%= Core.UniswapV3Factory.address %>",
    "<%= WETH.Token.address %>",
]
depends = ["clone.Core", "pull.WETH"]


[deploy.NFTDescriptor]
artifact = "NFTDescriptor"

[deploy.NonfungibleTokenPositionDescriptor]
artifact = "NonfungibleTokenPositionDescriptor"
args = [
    "<%= AddressZero %>", # TODO: use actual WETH address
    "<%= formatBytes32String(settings.nativeCurrencyLabel) %>"
]

libraries.NFTDescriptor = "<%= NFTDescriptor.address %>"

depends = ["deploy.NFTDescriptor", "var.main"]

[deploy.TransparentUpgradeableProxy]
artifact = "TransparentUpgradeableProxy"
args = [
    "<%= NonfungibleTokenPositionDescriptor.address %>",
    "<%= ProxyAdmin.address %>",
    "0x"
]
depends = ["deploy.NonfungibleTokenPositionDescriptor", "deploy.ProxyAdmin"]

[deploy.NonfungiblePositionManager]
artifact = "NonfungiblePositionManager"
args = [
    "<%= Core.UniswapV3Factory.address %>",
    "<%= WETH.Token.address %>",
    "<%= NonfungibleTokenPositionDescriptor.address %>"
]
depends = ["deploy.NonfungibleTokenPositionDescriptor", "pull.WETH", "clone.Core"]

# V3 migrator really isnt needed for V3 but I put the theoretical deployment here anyway
#[deploy.V3Migrator]
#artifact = "V3Migrator"
#from = "<%= settings.deployer %>"

#args = [
#    "<%= imports.Core.contracts.UniswapV3Factory.address %>",
#    "<%= AddressZero %>", # TODO: use actual WETH address
#    "<%= contracts.NonfungiblePositionManager.address %>"
#]

#depends = ["contract.NonfungiblePositionManager"]

[invoke.setOwner]
target = ["Core.UniswapV3Factory"]
func = "setOwner"
args = ["<%= settings.owner %>"]
fromCall.func = "owner"
